import { CloseRounded, FilterAltRounded } from "@mui/icons-material";
import { Box, Button, FormControl, InputLabel, MenuItem, Modal, Select, Typography } from "@mui/material";
import { emptyPromotionFilters, filterYears, getYearFilterValue, PromotionFilters } from "../context/AppContext";

const categories = ["All", "Skincare", "Fragrance", "Makeup", "Haircare"];
const retailers = ["All", "Rossmann Polska", "Hebe", "Douglas Polska", "Super-Pharm", "Natura", "Kontigo", "Fryzjerzy.pl", "Cocolita"];

export default function PromotionFilterModal({ open, filters, onClose, onApply }: { open: boolean; filters: PromotionFilters; onClose: () => void; onApply: (filters: PromotionFilters) => void }) {
  const update = (field: keyof PromotionFilters, value: string) => onApply({ ...filters, [field]: value });
  const selectedYear = getYearFilterValue(filters.fromDate);
  const updateYear = (year: string) => onApply({ ...filters, fromDate: year ? `${year}-01-01` : "", toDate: year ? `${year}-12-31` : "" });
  return <Modal open={open} onClose={onClose} aria-labelledby="promotion-filter-title"><Box className="absolute left-1/2 top-1/2 w-[calc(100%-32px)] max-w-[560px] -translate-x-1/2 -translate-y-1/2 rounded-2xl bg-white p-4 shadow-2xl"><Box className="mb-4 flex items-start justify-between gap-4" id="promotion-filter-title"><Box><Box className="flex items-center gap-2"><FilterAltRounded sx={{ color: "#286e5e" }} /><span className="font-bold text-[#173c35]">Promotion filters</span></Box><span className="text-xs text-[#82908b]">Filter products, campaigns, and store offers.</span></Box><Button onClick={onClose} sx={{ minWidth: 40, color: "#65736f" }}><CloseRounded /></Button></Box><Box className="grid grid-cols-1 gap-4 sm:grid-cols-2"><FormControl fullWidth><InputLabel>Product category</InputLabel><Select label="Product category" value={filters.category} onChange={(event) => update("category", event.target.value)}>{categories.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel>Retailer / store</InputLabel><Select label="Retailer / store" value={filters.retailer} onChange={(event) => update("retailer", event.target.value)}>{retailers.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel>Discount level</InputLabel><Select label="Discount level" value={filters.discount} onChange={(event) => update("discount", event.target.value)}>{["All", "10%+", "20%+", "25%+", "30%+"].map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel>Market</InputLabel><Select label="Market" value={filters.market} onChange={(event) => update("market", event.target.value)}>{["PL", "CZ"].map((market) => <MenuItem key={market} value={market}>{market}</MenuItem>)}</Select></FormControl><Box className="flex items-center gap-2 sm:col-span-2"><Typography sx={{ color: "#65736f", fontSize: 12, minWidth: 105 }}>Promotion year</Typography><Select size="small" displayEmpty value={selectedYear} onChange={(event) => updateYear(event.target.value)} sx={{ flex: 1, maxWidth: 220 }}><MenuItem value="">All years</MenuItem>{filterYears.map((year) => <MenuItem key={year} value={year}>{year}</MenuItem>)}</Select></Box></Box><Box className="mt-4 flex justify-end gap-2"><Button onClick={() => onApply(emptyPromotionFilters)} sx={{ color: "#65736f", textTransform: "none" }}>Clear filters</Button><Button onClick={onClose} variant="contained" sx={{ backgroundColor: "#286e5e", textTransform: "none" }}>Apply filters</Button></Box></Box></Modal>;
}
