// Generates supabase/seed.sql from the existing frontend data files, so the
// local DB starts with the same retailers/brands/categories the UI already
// hardcodes, plus a sample of promotions from products.json for testing.
// Re-run this any time those source files change: node scripts/generate-seed.js

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const root = path.join(__dirname, "..");

function extractArray(fileText, constName) {
  const re = new RegExp(`export const ${constName}\\s*=\\s*\\[([\\s\\S]*?)\\]\\s*as const`);
  const match = fileText.match(re);
  if (!match) throw new Error(`Could not find ${constName}`);
  const body = match[1];
  const items = [];
  const stringRe = /"((?:[^"\\]|\\.)*)"/g;
  let m;
  while ((m = stringRe.exec(body))) {
    items.push(m[1]);
  }
  return items;
}

function esc(value) {
  if (value === null || value === undefined) return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
}

const retailersTs = fs.readFileSync(path.join(root, "src/data/retailers.ts"), "utf8");
const brandsTs = fs.readFileSync(path.join(root, "src/data/brands.ts"), "utf8");
const products = JSON.parse(fs.readFileSync(path.join(root, "src/data/products.json"), "utf8"));

const plRetailers = extractArray(retailersTs, "plRetailers");
const czRetailers = extractArray(retailersTs, "czDummyRetailers");
const sephoraBrands = extractArray(brandsTs, "sephoraBrands");
const czBrands = extractArray(brandsTs, "czDummyBrands");
const categories = Array.from(new Set(products.map((p) => p.category))).sort();

const lines = [];
lines.push("-- Auto-generated by scripts/generate-seed.js. Do not edit by hand.");
lines.push("");

lines.push("-- Retailers");
for (const name of plRetailers) {
  lines.push(
    `insert into retailers (name, market, is_client) values (${esc(name)}, 'PL', ${name === "sephora"}) on conflict (name, market) do nothing;`,
  );
}
for (const name of czRetailers) {
  lines.push(
    `insert into retailers (name, market, is_client) values (${esc(name)}, 'CZ', false) on conflict (name, market) do nothing;`,
  );
}
lines.push("");

lines.push("-- Brands");
for (const name of sephoraBrands) {
  lines.push(`insert into brands (name, market) values (${esc(name)}, 'PL') on conflict (name, market) do nothing;`);
}
for (const name of czBrands) {
  lines.push(`insert into brands (name, market) values (${esc(name)}, 'CZ') on conflict (name, market) do nothing;`);
}
// The product catalog references some brands (competitor-carried, not in
// Sephora's own A-Z directory) that aren't in either list above — add those
// too so every promotion's brand FK resolves. Mirrors the "add a brand
// inline during entry" behavior from the client spec.
const seenBrands = new Set([...sephoraBrands.map((n) => `${n}|PL`), ...czBrands.map((n) => `${n}|CZ`)]);
for (const p of products) {
  const key = `${p.brand}|${p.market}`;
  if (seenBrands.has(key)) continue;
  seenBrands.add(key);
  lines.push(`insert into brands (name, market) values (${esc(p.brand)}, ${esc(p.market)}) on conflict (name, market) do nothing;`);
}
lines.push("");

lines.push("-- Categories");
for (const name of categories) {
  lines.push(`insert into categories (name) values (${esc(name)}) on conflict (name) do nothing;`);
}
lines.push("");

lines.push("-- Sample promotions (from the existing static catalog, for local testing only —");
lines.push("-- real historical data migration is a separate Phase 1b work package).");
for (const p of products) {
  const promotionId = crypto.randomUUID();
  const discountText = `-${p.competitorDiscount}%`;
  lines.push(
    `insert into promotions (id, market, retailer_id, category_id, name, date_from, date_to, discount_text, notes, promotion_type, price_after_discount, status, source) ` +
      `values (${esc(promotionId)}, ${esc(p.market)}, ` +
      `(select id from retailers where name = ${esc(p.retailer)} and market = ${esc(p.market)}), ` +
      `(select id from categories where name = ${esc(p.category)}), ` +
      `${esc(p.promotionName)}, ${esc(p.fromDate)}, ${esc(p.toDate)}, ${esc(discountText)}, ${esc(p.terms)}, 'Fixed promotion', ${p.priceAfterDiscount ?? "null"}, 'approved', 'manual');`,
  );
  lines.push(
    `insert into promotion_brands (promotion_id, brand_id) values (${esc(promotionId)}, ` +
      `(select id from brands where name = ${esc(p.brand)} and market = ${esc(p.market)})) on conflict do nothing;`,
  );
}

fs.writeFileSync(path.join(root, "supabase/seed.sql"), lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${plRetailers.length + czRetailers.length} retailers, ${sephoraBrands.length + czBrands.length} brands, ${categories.length} categories, ${products.length} promotions)`);
